### ISSUE TITLE
Bug when using ClassicApi

### ISSUE THREAD

**Issue by Zergei** [a3st/RetailUI#2]
got a bug using this addon https://gitlab.com/Tsoukie/classicapi
the bug:

1x RetailUI-1.2.0\Modules\ActionBar.lua:1198: attempt to index local 'widgetOptions' (a nil value)
RetailUI-1.2.0\Core.lua:109: in function `CheckSettingsExists'
RetailUI-1.2.0\Modules\ActionBar.lua:1125: in function `?'
CallbackHandler-1.0-7:145: in function <...Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-7:90: in function `Fire'
AceEvent-3.0-4 (RetailUI):120: in function <...e\AddOns\RetailUI\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:398:
 Enable = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:325:
 RegisterChatCommand = <function> @ RetailUI\Libs\AceConsole-3.0\AceConsole-3.0.lua:85:
 EnableModule = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:363:
 modules = <table> {}
 GetModule = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:241:
 IterateEmbeds = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:473:
 SecureHook = <function> @ RetailUI\Libs\AceHook-3.0\AceHook-3.0.lua:335:
 defaultModuleLibraries = <table> {}
 repExpBar = RUI_RepExpBar {}
 UnregisterChatCommand = <function> @ RetailUI\Libs\AceConsole-3.0\AceConsole-3.0.lua:111:
 RawHookScript = <function> @ RetailUI\Libs\AceHook-3.0\AceHook-3.0.lua:394:
 baseName = "RetailUI"
 Printf = <function> @ RetailUI\Libs\AceConsole-3.0\AceConsole-3.0.lua:69:
 GetName = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:310:
 SetDefaultModulePrototype = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:440:
 ShowEditorTest = <function> @ RetailUI\Modules\ActionBar.lua:1215:
 UpdateWidgets = <function> @ RetailUI\Modules\ActionBar.lua:1195:
 LoadDefaultSettings = <function> @ RetailUI\Modules\ActionBar.lua:1139:
 name = "RetailUI_ActionBar"
 PET_BAR_UPDATE = <function> @ RetailUI\Modules\ActionBar.lua:1130:
 IsEnabled = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:482:
 orderedModules = <table> {}
 PLAYER_ENTERING_WORLD = <function> @ RetailUI\Modules\ActionBar.lua:1094:
 DisableModule = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:381:
 OnDisable = <function> @ RetailUI\Modules\ActionBar.lua:1074:
 OnEnable = <function> @ RetailUI\Modules\ActionBar.lua:1002:
 microMenuBar = RUI_MicroMenuBar {}
 actionBars = <table> {}
 RegisterMessage = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116:
 GetArgs = <function> @ RetailUI\Libs\AceConsole-3.0\AceConsole-3.0.lua:144:
 Print = <function> @ RetailUI\Libs\AceConsole-3.0\AceConsole-3.0.lua:54:
 bagsBar = RUI_BagsBar {}
 IsHooked = <function> @ RetailUI\Libs\AceHook-3.0\AceHook-3.0.lua:492:
 NewModule = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:266:
 UnregisterAllEvents = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200:
 IsModule = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:248:
 SendMessage = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85:
 SetDefaultModuleState = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:418:
 UnregisterMessage = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179:
 defaultModuleState = true
 SetEnabledState = <function> @ RetailUI\Libs\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ RetailUI\Libs\AceHook-3.0\AceHook-3.0.lua:273:
 enabledState = true
 hooks = <table> {}
 RegisterEvent = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116:
 UnregisterAllMessages = <function> @ !!!ClassicAPI\Lib\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200:
 UnhookAll = <function> @ RetailUI\Libs\AceHook-3.0\AceHook-3.0.lua:476:
 Unho
  ---

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by a3st** [comment]
Fixed in last commit
